env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/docker-credential-mock
    goos:
      - darwin
      - linux
      - windows
    binary: docker-credential-mock
